//--------------------------------------------------------------------------
//
// Errors 
//
//--------------------------------------------------------------------------

#pragma once

namespace SDXEngine
{
	enum SDXErrorId
	{
		SDX_ERROR_NONE = 0,

		// App errors
		SDX_ERROR_APPCLASSREG_FAIL,
		SDX_ERROR_CREATEWINDOW_FAIL,

		// DirectX errors
		SDX_ERROR_DEVICE_CREATE_FAILED,
		SDX_ERROR_DEVICE_ALREADY_EXIST,
		SDX_ERROR_DEVICE_DIRECTX11_NOTSUPPORTED,
		SDX_ERROR_DEVICE_NOT_CREATED,
		SDX_ERROR_CHECKMSAA_FAILED,

		SDX_ERROR_SWAPCHAIN_CREATE_FAILED,
		SDX_ERROR_SWAPCHAIN_ALREADY_EXIST,
		SDX_ERROR_SWAPCHAIN_NO_SET_OUTPUTWINDOW,
		SDX_ERROR_SWAPCHAIN_NOT_CREATED,
		SDX_ERROR_SWAPCHAIN_PRESENT_FAILED,

		SDX_ERROR_RENDERTARGETVIEW_CREATE_FAILED,
		SDX_ERROR_RENDERTARGETVIEW_ALREADY_EXIST,
		SDX_ERROR_RENDERTARGETVIEW_NOT_CREATED,

		SDX_ERROR_DEPTHSTENCIL_ALREADY_EXIST,
		SDX_ERROR_DEPTHSTENCIL_NOT_CREATED,

		SDX_ERROR_VERTEXINPUTLAYOUT_ALREADY_EXIST,
		SDX_ERROR_VERTEXINPUTLAYOUT_NOT_CREATED,
		SDX_ERROR_VERTEXINPUTLAYOUT_UNKNOWN_VERTEX_TYPE,

		// Direct2D errors
		SDX_ERROR_DIRECT2D_NULLPTR_SET,
		SDX_ERROR_DIRECT2D_NOT_SET_DIRECTX,
		SDX_ERROR_DIRECT2D_DEVICE_NOT_CREATED,
		SDX_ERROR_DIRECT2D_DEVICE_ALREADY_CREATED,
		SDX_ERROR_DIRECT2D_DEVICE_CREATE_FAILED,
		SDX_ERROR_DIRECT2D_BITMAPRENDERTARGET_CREATE_FAILED,
		SDX_ERROR_DIRECT2D_BITMAPRENDERTARGET_ALREADY_CREATED,
		SDX_ERROR_DIRECT2D_INITTEXTFORMATS_FAILED,
		SDX_ERROR_DIRECT2D_CREATEBURSHES_FAILED,
		SDX_ERROR_DIRECT2D_TEXTFORMAT_NOT_SETUP,
		SDX_ERROR_DIRECT2D_SETUPTEXTFORMAT_FAILED,
		SDX_ERROR_DIRECT2D_DRAWTEXT_FAILED,

		// Renderer Errors
		SDX_ERROR_RENDERER_CLIENTAREA_NOT_SET,
		SDX_ERROR_RENDERER_OUTPUTWINDOW_NOT_SET,
		SDX_ERROR_RENDERER_INITIALISE_FAILED,

		SDX_ERROR_RENDERER_VERTEXSHADER_ALREADY_CREATED,
		SDX_ERROR_RENDERER_PIXELSHADER_ALREADY_CREATED,
		SDX_ERROR_RENDERER_VERTEXSHADER_CREATE_FAILED,
		SDX_ERROR_RENDERER_PIXELSHADER_CREATE_FAILED,
		SDX_ERROR_RENDERER_INPUTLAYOUT_CREATE_FAILED,
		SDX_ERROR_RENDERER_CONSTANTBUFFER_BIND_FAILED,
		SDX_ERROR_RENDERER_CONSTANTBUFFER_NOT_BOUND,

		// DirectX Compiler errors
		SDX_ERROR_DXCOMPILER_COMPILE_INVALID_ARGS,
		SDX_ERROR_DXCOMPILER_COMPILE_FAILED,

		// MeshData errors
		SDX_ERROR_MESHDATA_VERTEXARRAY_ALREADY_CREATED,
		SDX_ERROR_MESHDATA_CREATE_VERTEXARRAY_COUNT_ZERO,
		SDX_ERROR_MESHDATA_UNKNOWN_VERTEXTYPE,
		SDX_ERROR_MESHDATA_INDEXARRAY_ALREADY_CREATED,
		SDX_ERROR_MESHDATA_CREATE_INDEXARRAY_COUNT_ZERO,

		// SDXLog errors
		SDX_ERROR_LOG_OPEN_FAILED,
		SDX_ERROR_LOG_NO_FILE_OPEN,
		SDX_ERROR_LOG_FILE_ALREADY_OPEN,

		SDX_ERROR_UNKNOWN
	};

}