#include "stdafx.h"
#include "SDXErrors.h"

using namespace SDXEngine;

bool SDXEngine::IsError(SDXErrorId error)
{
	return error != SDXErrorId::SDX_ERROR_NONE ? true : false;
}


SDXErrorHelper* SDXErrorHelper::_instance = nullptr;

SDXErrorHelper::SDXErrorHelper()
{
	m_errorMap = 
	{ 
		{ SDXErrorId::SDX_ERROR_NONE, "SDX_ERROR_NONE" },

		{ SDXErrorId::SDX_ERROR_DEVICE_CREATE_FAILED, "SDX_ERROR_DEVICE_CREATE_FAILED" },
		{ SDXErrorId::SDX_ERROR_DEVICE_ALREADY_EXIST, "SDX_ERROR_DEVICE_ALREADY_EXIST" },
		{ SDXErrorId::SDX_ERROR_DEVICE_DIRECTX11_NOTSUPPORTED, "SDX_ERROR_DEVICE_DIRECTX11_NOTSUPPORTED" },
		{ SDXErrorId::SDX_ERROR_DEVICE_NOT_CREATED, "SDX_ERROR_DEVICE_NOT_CREATED" },
		{ SDXErrorId::SDX_ERROR_CHECKMSAA_FAILED, "SDX_ERROR_CHECKMSAA_FAILED" },
		{ SDXErrorId::SDX_ERROR_SWAPCHAIN_CREATE_FAILED, "SDX_ERROR_SWAPCHAIN_CREATE_FAILED" },
		{ SDXErrorId::SDX_ERROR_SWAPCHAIN_ALREADY_EXIST, "SDX_ERROR_SWAPCHAIN_ALREADY_EXIST" },
		{ SDXErrorId::SDX_ERROR_SWAPCHAIN_NO_SET_OUTPUTWINDOW, "SDX_ERROR_SWAPCHAIN_NO_SET_OUTPUTWINDOW" },
		{ SDXErrorId::SDX_ERROR_SWAPCHAIN_NOT_CREATED, "SDX_ERROR_SWAPCHAIN_NOT_CREATED" },
		{ SDXErrorId::SDX_ERROR_SWAPCHAIN_PRESENT_FAILED, "SDX_ERROR_SWAPCHAIN_PRESENT_FAILED" },
		{ SDXErrorId::SDX_ERROR_SWAPCHAIN_INVALID_MSAAQUALITY, "SDX_ERROR_SWAPCHAIN_INVALID_MSAAQUALITY" },

		{ SDXErrorId::SDX_ERROR_RENDERTARGETVIEW_CREATE_FAILED, "SDX_ERROR_RENDERTARGETVIEW_CREATE_FAILED" },
		{ SDXErrorId::SDX_ERROR_RENDERTARGETVIEW_ALREADY_EXIST, "SDX_ERROR_RENDERTARGETVIEW_ALREADY_EXIST" },
		{ SDXErrorId::SDX_ERROR_RENDERTARGETVIEW_NOT_CREATED, "SDX_ERROR_RENDERTARGETVIEW_NOT_CREATED" },

		{ SDXErrorId::SDX_ERROR_DEPTHSTENCIL_ALREADY_EXIST, "SDX_ERROR_DEPTHSTENCIL_ALREADY_EXIST" },
		{ SDXErrorId::SDX_ERROR_DEPTHSTENCIL_NOT_CREATED, "SDX_ERROR_DEPTHSTENCIL_NOT_CREATED" },

		{ SDXErrorId::SDX_ERROR_VERTEXINPUTLAYOUT_ALREADY_EXIST, "SDX_ERROR_VERTEXINPUTLAYOUT_ALREADY_EXIST" },
		{ SDXErrorId::SDX_ERROR_VERTEXINPUTLAYOUT_NOT_CREATED, "SDX_ERROR_VERTEXINPUTLAYOUT_NOT_CREATED" },
		{ SDXErrorId::SDX_ERROR_VERTEXINPUTLAYOUT_UNKNOWN_VERTEX_TYPE, "SDX_ERROR_VERTEXINPUTLAYOUT_UNKNOWN_VERTEX_TYPE" },

		{ SDXErrorId::SDX_ERROR_RASTERSTATECREATE_FAILED, "SDX_ERROR_RASTERSTATECREATE_FAILED" },
		{ SDXErrorId::SDX_ERROR_SAMPLERSTATECREATE_FAILED, "SDX_ERROR_SAMPLERSTATECREATE_FAILED" },
		{ SDXErrorId::SDX_ERROR_DEPTHSTENCILCREATE_FAILED, "SDX_ERROR_DEPTHSTENCILCREATE_FAILED" },

		{ SDXErrorId::SDX_ERROR_INVALIDDIRECTX_SETUPINFO, "SDX_ERROR_INVALIDDIRECTX_SETUPINFO" },

		{ SDXErrorId::SDX_ERROR_PARMETER_DIRECTX_NULLPTR, "SDX_ERROR_PARMETER_DIRECTX_NULLPTR" },

		{ SDXErrorId::SDX_ERROR_SHADER_COMPILE_FAILED, "SDX_ERROR_SHADER_COMPILE_FAILED" },
		{ SDXErrorId::SDX_ERROR_VERTEXSHADER_CREATE_FAILED, "SDX_ERROR_VERTEXSHADER_CREATE_FAILED" },
		{ SDXErrorId::SDX_ERROR_INPUTLAYOUT_CREATE_FAILED, "SDX_ERROR_INPUTLAYOUT_CREATE_FAILED" },
		{ SDXErrorId::SDX_ERROR_PIXELSHADER_CREATE_FAILED, "SDX_ERROR_PIXELSHADER_CREATE_FAILED" },

		{ SDXErrorId::SDX_ERROR_SHADERMGR_DIRECTX_NOTSET, "SDX_ERROR_SHADERMGR_DIRECTX_NOTSET" },

		{ SDXErrorId::SDX_ERROR_SHADERMGR_BIND_CONSTANT_FAILED, "SDX_ERROR_SHADERMGR_BIND_CONSTANT_FAILED" },
		{ SDXErrorId::SDX_ERROR_SHADERMGR_BIND_CONSTANT_ID_ALREADY_EXIST, "SDX_ERROR_SHADERMGR_BIND_CONSTANT_ID_ALREADY_EXIST" },

		{ SDXErrorId::SDX_ERROR_SHADERMGR_INVALID_SHADER_HANDLE, "SDX_ERROR_SHADERMGR_INVALID_SHADER_HANDLE" },
		{ SDXErrorId::SDX_ERROR_SHADERMGR_INVALID_CBUFFER_HANDLE, "SDX_ERROR_SHADERMGR_INVALID_CBUFFER_HANDLE" },
		{ SDXErrorId::SDX_ERROR_SHADERMGR_NULL_ID, "SDX_ERROR_SHADERMGR_NULL_ID" },

		{ SDXErrorId::SDX_ERROR_DIRECT2D_NOT_INITIALISED, "SDX_ERROR_DIRECT2D_NOT_INITIALISED" },
		{ SDXErrorId::SDX_ERROR_DIRECT2D_NULLPTR_SET, "SDX_ERROR_DIRECT2D_NULLPTR_SET" },
		{ SDXErrorId::SDX_ERROR_DIRECT2D_NOT_SET_DIRECTX, "SDX_ERROR_DIRECT2D_NOT_SET_DIRECTX" },
		{ SDXErrorId::SDX_ERROR_DIRECT2D_DEVICE_NOT_CREATED, "SDX_ERROR_DIRECT2D_DEVICE_NOT_CREATED" },
		{ SDXErrorId::SDX_ERROR_DIRECT2D_DEVICE_ALREADY_CREATED, "SDX_ERROR_DIRECT2D_DEVICE_ALREADY_CREATED" },
		{ SDXErrorId::SDX_ERROR_DIRECT2D_DEVICE_CREATE_FAILED, "SDX_ERROR_DIRECT2D_DEVICE_CREATE_FAILED" },
		{ SDXErrorId::SDX_ERROR_DIRECT2D_BITMAPRENDERTARGET_CREATE_FAILED, "SDX_ERROR_DIRECT2D_BITMAPRENDERTARGET_CREATE_FAILED" },
		{ SDXErrorId::SDX_ERROR_DIRECT2D_BITMAPRENDERTARGET_ALREADY_CREATED, "SDX_ERROR_DIRECT2D_BITMAPRENDERTARGET_ALREADY_CREATED" },
		{ SDXErrorId::SDX_ERROR_DIRECT2D_INITTEXTFORMATS_FAILED, "SDX_ERROR_DIRECT2D_INITTEXTFORMATS_FAILED" },
		{ SDXErrorId::SDX_ERROR_DIRECT2D_CREATEBURSHES_FAILED, "SDX_ERROR_DIRECT2D_CREATEBURSHES_FAILED" },
		{ SDXErrorId::SDX_ERROR_DIRECT2D_TEXTFORMAT_NOT_SETUP, "SDX_ERROR_DIRECT2D_TEXTFORMAT_NOT_SETUP" },
		{ SDXErrorId::SDX_ERROR_DIRECT2D_SETUPTEXTFORMAT_FAILED, "SDX_ERROR_DIRECT2D_SETUPTEXTFORMAT_FAILED" },
		{ SDXErrorId::SDX_ERROR_DIRECT2D_DRAWTEXT_FAILED, "SDX_ERROR_DIRECT2D_DRAWTEXT_FAILED" },

		{ SDXErrorId::SDX_ERROR_RENDERER_CLIENTAREA_NOT_SET, "SDX_ERROR_RENDERER_CLIENTAREA_NOT_SET" },
		{ SDXErrorId::SDX_ERROR_RENDERER_OUTPUTWINDOW_NOT_SET, "SDX_ERROR_RENDERER_OUTPUTWINDOW_NOT_SET" },
		{ SDXErrorId::SDX_ERROR_RENDERER_INITIALISE_FAILED, "SDX_ERROR_RENDERER_INITIALISE_FAILED" },

		{ SDXErrorId::SDX_ERROR_RENDERER_VERTEXSHADER_ALREADY_CREATED, "SDX_ERROR_RENDERER_VERTEXSHADER_ALREADY_CREATED" },
		{ SDXErrorId::SDX_ERROR_RENDERER_PIXELSHADER_ALREADY_CREATED, "SDX_ERROR_RENDERER_PIXELSHADER_ALREADY_CREATED" },
		{ SDXErrorId::SDX_ERROR_RENDERER_VERTEXSHADER_CREATE_FAILED, "SDX_ERROR_RENDERER_VERTEXSHADER_CREATE_FAILED" },
		{ SDXErrorId::SDX_ERROR_RENDERER_PIXELSHADER_CREATE_FAILED, "SDX_ERROR_RENDERER_PIXELSHADER_CREATE_FAILED" },
		{ SDXErrorId::SDX_ERROR_RENDERER_INPUTLAYOUT_CREATE_FAILED, "SDX_ERROR_RENDERER_INPUTLAYOUT_CREATE_FAILED" },
		{ SDXErrorId::SDX_ERROR_RENDERER_CONSTANTBUFFER_BIND_FAILED, "SDX_ERROR_RENDERER_CONSTANTBUFFER_BIND_FAILED" },
		{ SDXErrorId::SDX_ERROR_RENDERER_CONSTANTBUFFER_NOT_BOUND, "SDX_ERROR_RENDERER_CONSTANTBUFFER_NOT_BOUND" },

		{ SDXErrorId::SDX_ERROR_DXCOMPILER_COMPILE_INVALID_ARGS, "SDX_ERROR_DXCOMPILER_COMPILE_INVALID_ARGS" },
		{ SDXErrorId::SDX_ERROR_DXCOMPILER_COMPILE_FAILED, "SDX_ERROR_DXCOMPILER_COMPILE_FAILED" },

		{ SDXErrorId::SDX_ERROR_MESHDATA_VERTEXARRAY_ALREADY_CREATED, "SDX_ERROR_MESHDATA_VERTEXARRAY_ALREADY_CREATED" },
		{ SDXErrorId::SDX_ERROR_MESHDATA_CREATE_VERTEXARRAY_COUNT_ZERO, "SDX_ERROR_MESHDATA_CREATE_VERTEXARRAY_COUNT_ZERO" },
		{ SDXErrorId::SDX_ERROR_MESHDATA_UNKNOWN_VERTEXTYPE, "SDX_ERROR_MESHDATA_UNKNOWN_VERTEXTYPE" },
		{ SDXErrorId::SDX_ERROR_MESHDATA_INDEXARRAY_ALREADY_CREATED, "SDX_ERROR_MESHDATA_INDEXARRAY_ALREADY_CREATED" },
		{ SDXErrorId::SDX_ERROR_MESHDATA_CREATE_INDEXARRAY_COUNT_ZERO, "SDX_ERROR_MESHDATA_CREATE_INDEXARRAY_COUNT_ZERO" },

		{ SDXErrorId::SDX_ERROR_VERTEXBUFFER_ALREADY_LOADED, "SDX_ERROR_VERTEXBUFFER_ALREADY_LOADED" },
		{ SDXErrorId::SDX_ERROR_VERTEXBUFFER_MESHDATA_NULL, "SDX_ERROR_VERTEXBUFFER_MESHDATA_NULL" },
		{ SDXErrorId::SDX_ERROR_VERTEXBUFFER_UNKNOWN_VERTEXTYPE, "SDX_ERROR_VERTEXBUFFER_UNKNOWN_VERTEXTYPE" },
		{ SDXErrorId::SDX_ERROR_VERTEXBUFFER_DIRECTX_NULL, "SDX_ERROR_VERTEXBUFFER_DIRECTX_NULL" },
		{ SDXErrorId::SDX_ERROR_VERTEXBUFFER_CREATE_FAILED, "SDX_ERROR_VERTEXBUFFER_CREATE_FAILED" },

		{ SDXErrorId::SDX_ERROR_INDEXBUFFER_ALREADY_LOADED, "SDX_ERROR_INDEXBUFFER_ALREADY_LOADED" },
		{ SDXErrorId::SDX_ERROR_INDEXBUFFER_MESHDATA_NULL, "SDX_ERROR_INDEXBUFFER_MESHDATA_NULL" },
		{ SDXErrorId::SDX_ERROR_INDEXBUFFER_DIRECTX_NULL, "SDX_ERROR_INDEXBUFFER_DIRECTX_NULL" },
		{ SDXErrorId::SDX_ERROR_INDEXBUFFER_CREATE_FAILED, "SDX_ERROR_INDEXBUFFER_CREATE_FAILED" },

		{ SDXErrorId::SDX_ERROR_MESH_MESHDATA_NULL, "SDX_ERROR_MESH_MESHDATA_NULL" },
		{ SDXErrorId::SDX_ERROR_MESH_DIRECTX_NULL, "SDX_ERROR_MESH_DIRECTX_NULL" },

		{ SDXErrorId::SDX_ERROR_MATERIALMGR_ID_ALREADY_EXIST, "SDX_ERROR_MATERIALMGR_ID_ALREADY_EXIST" },

		{ SDXErrorId::SDX_ERROR_TEXTUREMGR_ID_ALREADY_EXIST, "SDX_ERROR_TEXTUREMGR_ID_ALREADY_EXIST" },
		{ SDXErrorId::SDX_ERROR_TEXTUREMGR_FAILED_CREATE, "SDX_ERROR_TEXTUREMGR_FAILED_CREATE" },

		{ SDXErrorId::SDX_ERROR_ASSETMGR_NOT_INITIALISED, "SDX_ERROR_ASSETMGR_NOT_INITIALISED" },
		{ SDXErrorId::SDX_ERROR_ASSETMGR_DUPLICATE_MESHID, "SDX_ERROR_ASSETMGR_DUPLICATE_MESHID" },

		{ SDXErrorId::SDX_ERROR_LOG_OPEN_FAILED, "SDX_ERROR_LOG_OPEN_FAILED" },
		{ SDXErrorId::SDX_ERROR_LOG_NO_FILE_OPEN, "SDX_ERROR_LOG_NO_FILE_OPEN" },
		{ SDXErrorId::SDX_ERROR_LOG_FILE_ALREADY_OPEN, "SDX_ERROR_LOG_FILE_ALREADY_OPEN" },

		{ SDXErrorId::SDX_ERROR_UNKNOWN, "SDX_ERROR_UNKNOWN" },

	};
}

SDXErrorHelper::~SDXErrorHelper()
{
}

SDXErrorHelper* SDXErrorHelper::GetInstance()
{
	if (_instance)
	{
		return _instance;
	}

	_instance = new SDXErrorHelper();
	return _instance;
}

void SDXErrorHelper::Release()
{
	if (_instance)
	{
		delete _instance;
		_instance = nullptr;
	}
}

std::string SDXErrorHelper::ErrorToString(SDXErrorId error)
{
	return m_errorMap.at(error);
}
